on:
  push:
    tags:
      - v*
name: Publish Package
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run publish $VSCE_TOKEN
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_ACCESS_TOKEN }}
